
-- Start of populate_category_table.sql
INSERT INTO category (category_id, category_name) VALUES ("c1", "1980s");
INSERT INTO category (category_id, category_name) VALUES ("c2", "2D");
INSERT INTO category (category_id, category_name) VALUES ("c3", "2D Fighter");
INSERT INTO category (category_id, category_name) VALUES ("c4", "3D Platformer");
INSERT INTO category (category_id, category_name) VALUES ("c5", "4X");
INSERT INTO category (category_id, category_name) VALUES ("c6", "Action");
INSERT INTO category (category_id, category_name) VALUES ("c7", "Action RPG");
INSERT INTO category (category_id, category_name) VALUES ("c8", "Adventure");
INSERT INTO category (category_id, category_name) VALUES ("c9", "Agriculture");
INSERT INTO category (category_id, category_name) VALUES ("c10", "America");
INSERT INTO category (category_id, category_name) VALUES ("c11", "Animation & Modeling");
INSERT INTO category (category_id, category_name) VALUES ("c12", "Anime");
INSERT INTO category (category_id, category_name) VALUES ("c13", "Arcade");
INSERT INTO category (category_id, category_name) VALUES ("c14", "Arena Shooter");
INSERT INTO category (category_id, category_name) VALUES ("c15", "Assassin");
INSERT INTO category (category_id, category_name) VALUES ("c16", "Atmospheric");
INSERT INTO category (category_id, category_name) VALUES ("c17", "Audio Production");
INSERT INTO category (category_id, category_name) VALUES ("c18", "Base-Building");
INSERT INTO category (category_id, category_name) VALUES ("c19", "Baseball");
INSERT INTO category (category_id, category_name) VALUES ("c20", "Basketball");
INSERT INTO category (category_id, category_name) VALUES ("c21", "Batman");
INSERT INTO category (category_id, category_name) VALUES ("c22", "Battle Royale");
INSERT INTO category (category_id, category_name) VALUES ("c23", "Beat 'em up");
INSERT INTO category (category_id, category_name) VALUES ("c24", "Board Game");
INSERT INTO category (category_id, category_name) VALUES ("c25", "Bowling");
INSERT INTO category (category_id, category_name) VALUES ("c26", "Building");
INSERT INTO category (category_id, category_name) VALUES ("c27", "Bullet Hell");
INSERT INTO category (category_id, category_name) VALUES ("c28", "Bullet Time");
INSERT INTO category (category_id, category_name) VALUES ("c29", "Capitalism");
INSERT INTO category (category_id, category_name) VALUES ("c30", "Card Game");
INSERT INTO category (category_id, category_name) VALUES ("c31", "Casual");
INSERT INTO category (category_id, category_name) VALUES ("c32", "Cats");
INSERT INTO category (category_id, category_name) VALUES ("c33", "Character Action Game");
INSERT INTO category (category_id, category_name) VALUES ("c34", "Character Customization");
INSERT INTO category (category_id, category_name) VALUES ("c35", "Choices Matter");
INSERT INTO category (category_id, category_name) VALUES ("c36", "Choose Your Own Adventure");
INSERT INTO category (category_id, category_name) VALUES ("c37", "City Builder");
INSERT INTO category (category_id, category_name) VALUES ("c38", "Classic");
INSERT INTO category (category_id, category_name) VALUES ("c39", "Clicker");
INSERT INTO category (category_id, category_name) VALUES ("c40", "Co-op");
INSERT INTO category (category_id, category_name) VALUES ("c41", "Colorful");
INSERT INTO category (category_id, category_name) VALUES ("c42", "Comedy");
INSERT INTO category (category_id, category_name) VALUES ("c43", "Competitive");
INSERT INTO category (category_id, category_name) VALUES ("c44", "Crafting");
INSERT INTO category (category_id, category_name) VALUES ("c45", "Crime");
INSERT INTO category (category_id, category_name) VALUES ("c46", "Cult Classic");
INSERT INTO category (category_id, category_name) VALUES ("c47", "Cute");
INSERT INTO category (category_id, category_name) VALUES ("c48", "Cyberpunk");
INSERT INTO category (category_id, category_name) VALUES ("c49", "Cycling");
INSERT INTO category (category_id, category_name) VALUES ("c50", "Dark");
INSERT INTO category (category_id, category_name) VALUES ("c51", "Dark Fantasy");
INSERT INTO category (category_id, category_name) VALUES ("c52", "Dark Humor");
INSERT INTO category (category_id, category_name) VALUES ("c53", "Dating Sim");
INSERT INTO category (category_id, category_name) VALUES ("c54", "Destruction");
INSERT INTO category (category_id, category_name) VALUES ("c55", "Detective");
INSERT INTO category (category_id, category_name) VALUES ("c56", "Difficult");
INSERT INTO category (category_id, category_name) VALUES ("c57", "Dinosaurs");
INSERT INTO category (category_id, category_name) VALUES ("c58", "Dog");
INSERT INTO category (category_id, category_name) VALUES ("c59", "Dragons");
INSERT INTO category (category_id, category_name) VALUES ("c60", "Driving");
INSERT INTO category (category_id, category_name) VALUES ("c61", "Dungeon Crawler");
INSERT INTO category (category_id, category_name) VALUES ("c62", "Early Access");
INSERT INTO category (category_id, category_name) VALUES ("c63", "Economy");
INSERT INTO category (category_id, category_name) VALUES ("c64", "Education");
INSERT INTO category (category_id, category_name) VALUES ("c65", "Exploration");
INSERT INTO category (category_id, category_name) VALUES ("c66", "FPS");
INSERT INTO category (category_id, category_name) VALUES ("c67", "Fantasy");
INSERT INTO category (category_id, category_name) VALUES ("c68", "Fast-Paced");
INSERT INTO category (category_id, category_name) VALUES ("c69", "Female Protagonist");
INSERT INTO category (category_id, category_name) VALUES ("c70", "Fighting");
INSERT INTO category (category_id, category_name) VALUES ("c71", "First-Person");
INSERT INTO category (category_id, category_name) VALUES ("c72", "Fishing");
INSERT INTO category (category_id, category_name) VALUES ("c73", "Flight");
INSERT INTO category (category_id, category_name) VALUES ("c74", "Football");
INSERT INTO category (category_id, category_name) VALUES ("c75", "Funny");
INSERT INTO category (category_id, category_name) VALUES ("c76", "Gambling");
INSERT INTO category (category_id, category_name) VALUES ("c77", "Game Development");
INSERT INTO category (category_id, category_name) VALUES ("c78", "Games Workshop");
INSERT INTO category (category_id, category_name) VALUES ("c79", "God Game");
INSERT INTO category (category_id, category_name) VALUES ("c80", "Golf");
INSERT INTO category (category_id, category_name) VALUES ("c81", "Gore");
INSERT INTO category (category_id, category_name) VALUES ("c82", "Gothic");
INSERT INTO category (category_id, category_name) VALUES ("c83", "Grand Strategy");
INSERT INTO category (category_id, category_name) VALUES ("c84", "Great Soundtrack");
INSERT INTO category (category_id, category_name) VALUES ("c85", "Hack and Slash");
INSERT INTO category (category_id, category_name) VALUES ("c86", "Hacking");
INSERT INTO category (category_id, category_name) VALUES ("c87", "Hidden Object");
INSERT INTO category (category_id, category_name) VALUES ("c88", "Historical");
INSERT INTO category (category_id, category_name) VALUES ("c89", "Hockey");
INSERT INTO category (category_id, category_name) VALUES ("c90", "Horror");
INSERT INTO category (category_id, category_name) VALUES ("c91", "Hunting");
INSERT INTO category (category_id, category_name) VALUES ("c92", "Illuminati");
INSERT INTO category (category_id, category_name) VALUES ("c93", "Indie");
INSERT INTO category (category_id, category_name) VALUES ("c94", "Inventory Management");
INSERT INTO category (category_id, category_name) VALUES ("c95", "Isometric");
INSERT INTO category (category_id, category_name) VALUES ("c96", "JRPG");
INSERT INTO category (category_id, category_name) VALUES ("c97", "Kickstarter");
INSERT INTO category (category_id, category_name) VALUES ("c98", "LEGO");
INSERT INTO category (category_id, category_name) VALUES ("c99", "Level Editor");
INSERT INTO category (category_id, category_name) VALUES ("c100", "Linear");
INSERT INTO category (category_id, category_name) VALUES ("c101", "Local Co-Op");
INSERT INTO category (category_id, category_name) VALUES ("c102", "Local Multiplayer");
INSERT INTO category (category_id, category_name) VALUES ("c103", "Lovecraftian");
INSERT INTO category (category_id, category_name) VALUES ("c104", "Magic");
INSERT INTO category (category_id, category_name) VALUES ("c105", "Management");
INSERT INTO category (category_id, category_name) VALUES ("c106", "Mars");
INSERT INTO category (category_id, category_name) VALUES ("c107", "Martial Arts");
INSERT INTO category (category_id, category_name) VALUES ("c108", "Massively Multiplayer");
INSERT INTO category (category_id, category_name) VALUES ("c109", "Match 3");
INSERT INTO category (category_id, category_name) VALUES ("c110", "Mature");
INSERT INTO category (category_id, category_name) VALUES ("c111", "Medieval");
INSERT INTO category (category_id, category_name) VALUES ("c112", "Memes");
INSERT INTO category (category_id, category_name) VALUES ("c113", "Metroidvania");
INSERT INTO category (category_id, category_name) VALUES ("c114", "Military");
INSERT INTO category (category_id, category_name) VALUES ("c115", "Mini Golf");
INSERT INTO category (category_id, category_name) VALUES ("c116", "Mining");
INSERT INTO category (category_id, category_name) VALUES ("c117", "Motocross");
INSERT INTO category (category_id, category_name) VALUES ("c118", "Multiplayer");
INSERT INTO category (category_id, category_name) VALUES ("c119", "Music");
INSERT INTO category (category_id, category_name) VALUES ("c120", "Mystery");
INSERT INTO category (category_id, category_name) VALUES ("c121", "Mythology");
INSERT INTO category (category_id, category_name) VALUES ("c122", "Narration");
INSERT INTO category (category_id, category_name) VALUES ("c123", "Naval");
INSERT INTO category (category_id, category_name) VALUES ("c124", "Ninja");
INSERT INTO category (category_id, category_name) VALUES ("c125", "Noir");
INSERT INTO category (category_id, category_name) VALUES ("c126", "Nudity");
INSERT INTO category (category_id, category_name) VALUES ("c127", "Offroad");
INSERT INTO category (category_id, category_name) VALUES ("c128", "Online Co-Op");
INSERT INTO category (category_id, category_name) VALUES ("c129", "Open World");
INSERT INTO category (category_id, category_name) VALUES ("c130", "Parkour");
INSERT INTO category (category_id, category_name) VALUES ("c131", "Party-Based RPG");
INSERT INTO category (category_id, category_name) VALUES ("c132", "Physics");
INSERT INTO category (category_id, category_name) VALUES ("c133", "Pirates");
INSERT INTO category (category_id, category_name) VALUES ("c134", "Pixel Graphics");
INSERT INTO category (category_id, category_name) VALUES ("c135", "Platformer");
INSERT INTO category (category_id, category_name) VALUES ("c136", "Point & Click");
INSERT INTO category (category_id, category_name) VALUES ("c137", "Political");
INSERT INTO category (category_id, category_name) VALUES ("c138", "Politics");
INSERT INTO category (category_id, category_name) VALUES ("c139", "Post-apocalyptic");
INSERT INTO category (category_id, category_name) VALUES ("c140", "Programming");
INSERT INTO category (category_id, category_name) VALUES ("c141", "Psychological");
INSERT INTO category (category_id, category_name) VALUES ("c142", "Psychological Horror");
INSERT INTO category (category_id, category_name) VALUES ("c143", "Puzzle");
INSERT INTO category (category_id, category_name) VALUES ("c144", "RPG");
INSERT INTO category (category_id, category_name) VALUES ("c145", "RPGMaker");
INSERT INTO category (category_id, category_name) VALUES ("c146", "RTS");
INSERT INTO category (category_id, category_name) VALUES ("c147", "Racing");
INSERT INTO category (category_id, category_name) VALUES ("c148", "Real-Time with Pause");
INSERT INTO category (category_id, category_name) VALUES ("c149", "Realistic");
INSERT INTO category (category_id, category_name) VALUES ("c150", "Relaxing");
INSERT INTO category (category_id, category_name) VALUES ("c151", "Remake");
INSERT INTO category (category_id, category_name) VALUES ("c152", "Replay Value");
INSERT INTO category (category_id, category_name) VALUES ("c153", "Resource Management");
INSERT INTO category (category_id, category_name) VALUES ("c154", "Retro");
INSERT INTO category (category_id, category_name) VALUES ("c155", "Rhythm");
INSERT INTO category (category_id, category_name) VALUES ("c156", "Robots");
INSERT INTO category (category_id, category_name) VALUES ("c157", "Rogue-like");
INSERT INTO category (category_id, category_name) VALUES ("c158", "Rogue-lite");
INSERT INTO category (category_id, category_name) VALUES ("c159", "Romance");
INSERT INTO category (category_id, category_name) VALUES ("c160", "Runner");
INSERT INTO category (category_id, category_name) VALUES ("c161", "Sandbox");
INSERT INTO category (category_id, category_name) VALUES ("c162", "Sci-fi");
INSERT INTO category (category_id, category_name) VALUES ("c163", "Sexual Content");
INSERT INTO category (category_id, category_name) VALUES ("c164", "Shoot 'Em Up");
INSERT INTO category (category_id, category_name) VALUES ("c165", "Shooter");
INSERT INTO category (category_id, category_name) VALUES ("c166", "Simulation");
INSERT INTO category (category_id, category_name) VALUES ("c167", "Singleplayer");
INSERT INTO category (category_id, category_name) VALUES ("c168", "Sniper");
INSERT INTO category (category_id, category_name) VALUES ("c169", "Soccer");
INSERT INTO category (category_id, category_name) VALUES ("c170", "Software");
INSERT INTO category (category_id, category_name) VALUES ("c171", "Souls-like");
INSERT INTO category (category_id, category_name) VALUES ("c172", "Space");
INSERT INTO category (category_id, category_name) VALUES ("c173", "Space Sim");
INSERT INTO category (category_id, category_name) VALUES ("c174", "Split Screen");
INSERT INTO category (category_id, category_name) VALUES ("c175", "Sports");
INSERT INTO category (category_id, category_name) VALUES ("c176", "Star Wars");
INSERT INTO category (category_id, category_name) VALUES ("c177", "Stealth");
INSERT INTO category (category_id, category_name) VALUES ("c178", "Steampunk");
INSERT INTO category (category_id, category_name) VALUES ("c179", "Story Rich");
INSERT INTO category (category_id, category_name) VALUES ("c180", "Strategy");
INSERT INTO category (category_id, category_name) VALUES ("c181", "Strategy RPG");
INSERT INTO category (category_id, category_name) VALUES ("c182", "Superhero");
INSERT INTO category (category_id, category_name) VALUES ("c183", "Supernatural");
INSERT INTO category (category_id, category_name) VALUES ("c184", "Surreal");
INSERT INTO category (category_id, category_name) VALUES ("c185", "Survival");
INSERT INTO category (category_id, category_name) VALUES ("c186", "Survival Horror");
INSERT INTO category (category_id, category_name) VALUES ("c187", "Swordplay");
INSERT INTO category (category_id, category_name) VALUES ("c188", "Tactical");
INSERT INTO category (category_id, category_name) VALUES ("c189", "Tanks");
INSERT INTO category (category_id, category_name) VALUES ("c190", "Third Person");
INSERT INTO category (category_id, category_name) VALUES ("c191", "Third-Person Shooter");
INSERT INTO category (category_id, category_name) VALUES ("c192", "Time Management");
INSERT INTO category (category_id, category_name) VALUES ("c193", "Time Manipulation");
INSERT INTO category (category_id, category_name) VALUES ("c194", "Top-Down");
INSERT INTO category (category_id, category_name) VALUES ("c195", "Tower Defense");
INSERT INTO category (category_id, category_name) VALUES ("c196", "Trading");
INSERT INTO category (category_id, category_name) VALUES ("c197", "Trading Card Game");
INSERT INTO category (category_id, category_name) VALUES ("c198", "Trains");
INSERT INTO category (category_id, category_name) VALUES ("c199", "Turn-Based");
INSERT INTO category (category_id, category_name) VALUES ("c200", "Turn-Based Combat");
INSERT INTO category (category_id, category_name) VALUES ("c201", "Turn-Based Strategy");
INSERT INTO category (category_id, category_name) VALUES ("c202", "Turn-Based Tactics");
INSERT INTO category (category_id, category_name) VALUES ("c203", "Twin Stick Shooter");
INSERT INTO category (category_id, category_name) VALUES ("c204", "Typing");
INSERT INTO category (category_id, category_name) VALUES ("c205", "Underwater");
INSERT INTO category (category_id, category_name) VALUES ("c206", "Utilities");
INSERT INTO category (category_id, category_name) VALUES ("c207", "VR");
INSERT INTO category (category_id, category_name) VALUES ("c208", "Vampire");
INSERT INTO category (category_id, category_name) VALUES ("c209", "Villain Protagonist");
INSERT INTO category (category_id, category_name) VALUES ("c210", "Violent");
INSERT INTO category (category_id, category_name) VALUES ("c211", "Visual Novel");
INSERT INTO category (category_id, category_name) VALUES ("c212", "Walking Simulator");
INSERT INTO category (category_id, category_name) VALUES ("c213", "War");
INSERT INTO category (category_id, category_name) VALUES ("c214", "Warhammer 40K");
INSERT INTO category (category_id, category_name) VALUES ("c215", "Web Publishing");
INSERT INTO category (category_id, category_name) VALUES ("c216", "Western");
INSERT INTO category (category_id, category_name) VALUES ("c217", "World War I");
INSERT INTO category (category_id, category_name) VALUES ("c218", "World War II");
INSERT INTO category (category_id, category_name) VALUES ("c219", "Wrestling");
INSERT INTO category (category_id, category_name) VALUES ("c220", "Zombies");
INSERT INTO category (category_id, category_name) VALUES ("c221", "Single-player");
INSERT INTO category (category_id, category_name) VALUES ("c222", "Multi-player");

-- End of populate_category_table.sql