-- Start of populate_developer_table.sql
INSERT INTO developer (developer_id, developer_name) VALUES ("d1", "Ellie");
INSERT INTO developer (developer_id, developer_name) VALUES ("d2", "07th Expansion");
INSERT INTO developer (developer_id, developer_name) VALUES ("d3", "1C Entertainment");
INSERT INTO developer (developer_id, developer_name) VALUES ("d4", "1C Game Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d5", "1C-SoftClub");
INSERT INTO developer (developer_id, developer_name) VALUES ("d6", "1C: Maddox Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d7", "1CC Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d8", "2D Heroes");
INSERT INTO developer (developer_id, developer_name) VALUES ("d9", "2K Australia");
INSERT INTO developer (developer_id, developer_name) VALUES ("d10", "2K Boston");
INSERT INTO developer (developer_id, developer_name) VALUES ("d11", "2K China");
INSERT INTO developer (developer_id, developer_name) VALUES ("d12", "2K Czech");
INSERT INTO developer (developer_id, developer_name) VALUES ("d13", "2K Marin");
INSERT INTO developer (developer_id, developer_name) VALUES ("d14", "343 Industries");
INSERT INTO developer (developer_id, developer_name) VALUES ("d15", "38 Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d16", "3D Avenue");
INSERT INTO developer (developer_id, developer_name) VALUES ("d17", "4A Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d18", "5th Cell Media");
INSERT INTO developer (developer_id, developer_name) VALUES ("d19", "777 Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d20", "89AM Studio");
INSERT INTO developer (developer_id, developer_name) VALUES ("d21", "@unepic_fran");
INSERT INTO developer (developer_id, developer_name) VALUES ("d22", "A.Y.std");
INSERT INTO developer (developer_id, developer_name) VALUES ("d23", "AL-GAME");
INSERT INTO developer (developer_id, developer_name) VALUES ("d24", "AMPLITUDE Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d25", "ARTDINK");
INSERT INTO developer (developer_id, developer_name) VALUES ("d26", "ARTDINK CORPORATION");
INSERT INTO developer (developer_id, developer_name) VALUES ("d27", "Abbey Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d28", "Abrakam SA");
INSERT INTO developer (developer_id, developer_name) VALUES ("d29", "Absorb Reality");
INSERT INTO developer (developer_id, developer_name) VALUES ("d30", "Abstraction Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d31", "Abstractive Works");
INSERT INTO developer (developer_id, developer_name) VALUES ("d32", "Acid Wizard Studio");
INSERT INTO developer (developer_id, developer_name) VALUES ("d33", "Adityaraj Rukhane, Adiart");
INSERT INTO developer (developer_id, developer_name) VALUES ("d34", "Admir Leka");
INSERT INTO developer (developer_id, developer_name) VALUES ("d35", "Adriaan de Jongh");
INSERT INTO developer (developer_id, developer_name) VALUES ("d36", "Afterthought LLC");
INSERT INTO developer (developer_id, developer_name) VALUES ("d37", "Airship Syndicate");
INSERT INTO developer (developer_id, developer_name) VALUES ("d38", "Airtight Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d39", "Akella");
INSERT INTO developer (developer_id, developer_name) VALUES ("d40", "Alastair John Jack");
INSERT INTO developer (developer_id, developer_name) VALUES ("d41", "Alda Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d42", "Alekseev");
INSERT INTO developer (developer_id, developer_name) VALUES ("d43", "Alexey Davydov");
INSERT INTO developer (developer_id, developer_name) VALUES ("d44", "Alexey Khazov");
INSERT INTO developer (developer_id, developer_name) VALUES ("d45", "Almost Human Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d46", "Altar Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d47", "Amanita Design");
INSERT INTO developer (developer_id, developer_name) VALUES ("d48", "Amaterasu Software");
INSERT INTO developer (developer_id, developer_name) VALUES ("d49", "Amistech Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d50", "Anamik Majumdar");
INSERT INTO developer (developer_id, developer_name) VALUES ("d51", "Anatoliy Loginovskikh");
INSERT INTO developer (developer_id, developer_name) VALUES ("d52", "Andr Bertaglia");
INSERT INTO developer (developer_id, developer_name) VALUES ("d53", "Anea_Duo_Dev");
INSERT INTO developer (developer_id, developer_name) VALUES ("d54", "Anisoptera Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d55", "Anthony Rotondo");
INSERT INTO developer (developer_id, developer_name) VALUES ("d56", "Anthony Septim");
INSERT INTO developer (developer_id, developer_name) VALUES ("d57", "Antimatter Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d58", "Apoapsis Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d59", "Aquiris Game Studio");
INSERT INTO developer (developer_id, developer_name) VALUES ("d60", "Arc System Works");
INSERT INTO developer (developer_id, developer_name) VALUES ("d61", "Ardi Studio");
INSERT INTO developer (developer_id, developer_name) VALUES ("d62", "Arkane Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d63", "Arrowhead Game Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d64", "ArteG");
INSERT INTO developer (developer_id, developer_name) VALUES ("d65", "Artur Rezende");
INSERT INTO developer (developer_id, developer_name) VALUES ("d66", "Ascaron");
INSERT INTO developer (developer_id, developer_name) VALUES ("d67", "Aspyr (Linux)");
INSERT INTO developer (developer_id, developer_name) VALUES ("d68", "Aspyr (Mac)");
INSERT INTO developer (developer_id, developer_name) VALUES ("d69", "Aspyr (Mac, Linux, & Windows Update)");
INSERT INTO developer (developer_id, developer_name) VALUES ("d70", "Aspyr Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d71", "Asteristic Game Studio");
INSERT INTO developer (developer_id, developer_name) VALUES ("d72", "Asteroid Base");
INSERT INTO developer (developer_id, developer_name) VALUES ("d73", "Astronomic Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d74", "Athena Works");
INSERT INTO developer (developer_id, developer_name) VALUES ("d75", "AtomTeam");
INSERT INTO developer (developer_id, developer_name) VALUES ("d76", "Atomic Fabrik");
INSERT INTO developer (developer_id, developer_name) VALUES ("d77", "Atum Software");
INSERT INTO developer (developer_id, developer_name) VALUES ("d78", "AutoAttack Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d79", "Autonomic Interactive");
INSERT INTO developer (developer_id, developer_name) VALUES ("d80", "Avalanche Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d81", "Axolot Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d82", "BANDAI NAMCO Entertainment Inc.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d83", "BANDAI NAMCO Studio");
INSERT INTO developer (developer_id, developer_name) VALUES ("d84", "BANDAI NAMCO Studio Inc.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d85", "BANDAI NAMCO Studios Inc.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d86", "Back To Basics Gaming");
INSERT INTO developer (developer_id, developer_name) VALUES ("d87", "BadFly Interactive, a.s.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d88", "BadWolf Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d89", "Bankroll Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d90", "Bare Mettle Entertainment");
INSERT INTO developer (developer_id, developer_name) VALUES ("d91", "Barrel Roll Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d92", "Batterystaple Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d93", "BattleGoat Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d94", "Beam Team Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d95", "BeamNG");
INSERT INTO developer (developer_id, developer_name) VALUES ("d96", "Beamdog");
INSERT INTO developer (developer_id, developer_name) VALUES ("d97", "Beatshapers");
INSERT INTO developer (developer_id, developer_name) VALUES ("d98", "Bedtime Digital Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d99", "Beenox");
INSERT INTO developer (developer_id, developer_name) VALUES ("d100", "Behaviour Digital Inc.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d101", "Behaviour Interactive");
INSERT INTO developer (developer_id, developer_name) VALUES ("d102", "Ben Garney");
INSERT INTO developer (developer_id, developer_name) VALUES ("d103", "Besedka Games Studio");
INSERT INTO developer (developer_id, developer_name) VALUES ("d104", "Best Way");
INSERT INTO developer (developer_id, developer_name) VALUES ("d105", "Bethesda Game Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d106", "Big Ant Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d107", "Big Corporation");
INSERT INTO developer (developer_id, developer_name) VALUES ("d108", "Big Huge Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d109", "BigBlaze Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d110", "Bigmoon Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d111", "BioWare");
INSERT INTO developer (developer_id, developer_name) VALUES ("d112", "Bit Golem");
INSERT INTO developer (developer_id, developer_name) VALUES ("d113", "Bitbox Ltd.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d114", "Black Eye Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d115", "Black Isle Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d116", "Black Lab Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d117", "Black Lime Studio");
INSERT INTO developer (developer_id, developer_name) VALUES ("d118", "Black Sea Studios Ltd");
INSERT INTO developer (developer_id, developer_name) VALUES ("d119", "Blackbird Interactive");
INSERT INTO developer (developer_id, developer_name) VALUES ("d120", "Blacklight Interactive");
INSERT INTO developer (developer_id, developer_name) VALUES ("d121", "Blackmill Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d122", "Blaiz Entertainment");
INSERT INTO developer (developer_id, developer_name) VALUES ("d123", "Blake Fix");
INSERT INTO developer (developer_id, developer_name) VALUES ("d124", "BlankMediaGames");
INSERT INTO developer (developer_id, developer_name) VALUES ("d125", "Blastoid Entertainment");
INSERT INTO developer (developer_id, developer_name) VALUES ("d126", "Blind Squirrel");
INSERT INTO developer (developer_id, developer_name) VALUES ("d127", "Bloober Team SA");
INSERT INTO developer (developer_id, developer_name) VALUES ("d128", "Blue Bottle Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d129", "Blue Byte");
INSERT INTO developer (developer_id, developer_name) VALUES ("d130", "Blue Isle Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d131", "Bohemia Interactive");
INSERT INTO developer (developer_id, developer_name) VALUES ("d132", "Boneloaf");
INSERT INTO developer (developer_id, developer_name) VALUES ("d133", "Bossa Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d134", "Boxelware");
INSERT INTO developer (developer_id, developer_name) VALUES ("d135", "Brace Yourself Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d136", "BrainStrainStudios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d137", "Brandon van Doorn");
INSERT INTO developer (developer_id, developer_name) VALUES ("d138", "Brightrock Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d139", "Brilliant Game Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d140", "Brilliant Skies Ltd.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d141", "Bugbear");
INSERT INTO developer (developer_id, developer_name) VALUES ("d142", "Bugbear Entertainment");
INSERT INTO developer (developer_id, developer_name) VALUES ("d143", "CAPCOM CO., LTD.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d144", "CAPCOM Co., Ltd.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d145", "CD PROJEKT RED");
INSERT INTO developer (developer_id, developer_name) VALUES ("d146", "CI Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d147", "COMPILE HEART");
INSERT INTO developer (developer_id, developer_name) VALUES ("d148", "COMPILE HEART Co., Ltd.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d149", "CREATIVE ASSEMBLY");
INSERT INTO developer (developer_id, developer_name) VALUES ("d150", "Campo Santo");
INSERT INTO developer (developer_id, developer_name) VALUES ("d151", "Camshaft Software");
INSERT INTO developer (developer_id, developer_name) VALUES ("d152", "Capcom");
INSERT INTO developer (developer_id, developer_name) VALUES ("d153", "Capcom Game Studio Vancouver");
INSERT INTO developer (developer_id, developer_name) VALUES ("d154", "Capcom Vancouver");
INSERT INTO developer (developer_id, developer_name) VALUES ("d155", "Capybara Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d156", "CarX Technologies");
INSERT INTO developer (developer_id, developer_name) VALUES ("d157", "Cats Who Play");
INSERT INTO developer (developer_id, developer_name) VALUES ("d158", "Cavedog Entertainment");
INSERT INTO developer (developer_id, developer_name) VALUES ("d159", "Charyb Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d160", "Childish Things");
INSERT INTO developer (developer_id, developer_name) VALUES ("d161", "Chongqing Shangshixuan Technology Co., Ltd.,");
INSERT INTO developer (developer_id, developer_name) VALUES ("d162", "Chris Sawyer Productions");
INSERT INTO developer (developer_id, developer_name) VALUES ("d163", "Christian Whitehead");
INSERT INTO developer (developer_id, developer_name) VALUES ("d164", "Chuck Productions");
INSERT INTO developer (developer_id, developer_name) VALUES ("d165", "Chucklefish");
INSERT INTO developer (developer_id, developer_name) VALUES ("d166", "Circle Five Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d167", "City Interactive");
INSERT INTO developer (developer_id, developer_name) VALUES ("d168", "Clapfoot");
INSERT INTO developer (developer_id, developer_name) VALUES ("d169", "CleanWaterSoft");
INSERT INTO developer (developer_id, developer_name) VALUES ("d170", "Clickteam");
INSERT INTO developer (developer_id, developer_name) VALUES ("d171", "Code Club AB");
INSERT INTO developer (developer_id, developer_name) VALUES ("d172", "Code Horizon");
INSERT INTO developer (developer_id, developer_name) VALUES ("d173", "Code Mystics");
INSERT INTO developer (developer_id, developer_name) VALUES ("d174", "Codeglue");
INSERT INTO developer (developer_id, developer_name) VALUES ("d175", "Codemasters");
INSERT INTO developer (developer_id, developer_name) VALUES ("d176", "Codemasters Birmingham");
INSERT INTO developer (developer_id, developer_name) VALUES ("d177", "Codemasters Racing");
INSERT INTO developer (developer_id, developer_name) VALUES ("d178", "Codemasters Racing Studio");
INSERT INTO developer (developer_id, developer_name) VALUES ("d179", "Code}{atch");
INSERT INTO developer (developer_id, developer_name) VALUES ("d180", "Coffee Stain Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d181", "ColdGames");
INSERT INTO developer (developer_id, developer_name) VALUES ("d182", "Colossal Order Ltd.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d183", "Compile Heart");
INSERT INTO developer (developer_id, developer_name) VALUES ("d184", "ConcernedApe");
INSERT INTO developer (developer_id, developer_name) VALUES ("d185", "Conflux Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d186", "Coolhand Interactive");
INSERT INTO developer (developer_id, developer_name) VALUES ("d187", "Coreplay GmbH");
INSERT INTO developer (developer_id, developer_name) VALUES ("d188", "Crackshell");
INSERT INTO developer (developer_id, developer_name) VALUES ("d189", "Craneballs");
INSERT INTO developer (developer_id, developer_name) VALUES ("d190", "Crate Entertainment");
INSERT INTO developer (developer_id, developer_name) VALUES ("d191", "CreSpirit");
INSERT INTO developer (developer_id, developer_name) VALUES ("d192", "Creative Assembly");
INSERT INTO developer (developer_id, developer_name) VALUES ("d193", "CreativeForge Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d194", "Creobit");
INSERT INTO developer (developer_id, developer_name) VALUES ("d195", "Creoteam");
INSERT INTO developer (developer_id, developer_name) VALUES ("d196", "Cristian Ionescu");
INSERT INTO developer (developer_id, developer_name) VALUES ("d197", "Cristian Manolachi");
INSERT INTO developer (developer_id, developer_name) VALUES ("d198", "Criterion Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d199", "Croteam");
INSERT INTO developer (developer_id, developer_name) VALUES ("d200", "Croteam VR");
INSERT INTO developer (developer_id, developer_name) VALUES ("d201", "Crowbar Collective");
INSERT INTO developer (developer_id, developer_name) VALUES ("d202", "Crystal Dynamics");
INSERT INTO developer (developer_id, developer_name) VALUES ("d203", "Crytek");
INSERT INTO developer (developer_id, developer_name) VALUES ("d204", "Crytek Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d205", "Cyanide Studio");
INSERT INTO developer (developer_id, developer_name) VALUES ("d206", "Cyanide Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d207", "CyberConnect2");
INSERT INTO developer (developer_id, developer_name) VALUES ("d208", "CyberConnect2 Co. Ltd.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d209", "Cybernetik Design");
INSERT INTO developer (developer_id, developer_name) VALUES ("d210", "Czester16");
INSERT INTO developer (developer_id, developer_name) VALUES ("d211", "D-Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d212", "D247 Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d213", "DEADBIT");
INSERT INTO developer (developer_id, developer_name) VALUES ("d214", "DICE");
INSERT INTO developer (developer_id, developer_name) VALUES ("d215", "DIMPS");
INSERT INTO developer (developer_id, developer_name) VALUES ("d216", "DL Softworks");
INSERT INTO developer (developer_id, developer_name) VALUES ("d217", "DONTNOD Entertainment");
INSERT INTO developer (developer_id, developer_name) VALUES ("d218", "DUCK");
INSERT INTO developer (developer_id, developer_name) VALUES ("d219", "Daedalic Entertainment");
INSERT INTO developer (developer_id, developer_name) VALUES ("d220", "Dambuster Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d221", "Dan Fornace");
INSERT INTO developer (developer_id, developer_name) VALUES ("d222", "Daniel Mullins Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d223", "David OReilly");
INSERT INTO developer (developer_id, developer_name) VALUES ("d224", "Day 1 Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d225", "Days of Wonder");
INSERT INTO developer (developer_id, developer_name) VALUES ("d226", "Deadpan Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d227", "Deck 13");
INSERT INTO developer (developer_id, developer_name) VALUES ("d228", "Deck Nine");
INSERT INTO developer (developer_id, developer_name) VALUES ("d229", "Deck13");
INSERT INTO developer (developer_id, developer_name) VALUES ("d230", "Deck13 Hamburg");
INSERT INTO developer (developer_id, developer_name) VALUES ("d231", "Deep Silver Volition");
INSERT INTO developer (developer_id, developer_name) VALUES ("d232", "Defiant Development");
INSERT INTO developer (developer_id, developer_name) VALUES ("d233", "Dekovir Entertainment");
INSERT INTO developer (developer_id, developer_name) VALUES ("d234", "Denis Ovsyannikov");
INSERT INTO developer (developer_id, developer_name) VALUES ("d235", "Dennaton Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d236", "Devdan Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d237", "Devil's Details");
INSERT INTO developer (developer_id, developer_name) VALUES ("d238", "Diatomic Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d239", "Digdog Studio");
INSERT INTO developer (developer_id, developer_name) VALUES ("d240", "Digital Confectioners");
INSERT INTO developer (developer_id, developer_name) VALUES ("d241", "Digital Extremes");
INSERT INTO developer (developer_id, developer_name) VALUES ("d242", "DigitalDNA Games LLC");
INSERT INTO developer (developer_id, developer_name) VALUES ("d243", "Digitalmindsoft");
INSERT INTO developer (developer_id, developer_name) VALUES ("d244", "Dingaling");
INSERT INTO developer (developer_id, developer_name) VALUES ("d245", "Dinosaur Polo Club");
INSERT INTO developer (developer_id, developer_name) VALUES ("d246", "DistrictWare inc.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d247", "Doborog Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d248", "Dodge Roll");
INSERT INTO developer (developer_id, developer_name) VALUES ("d249", "DolphinBarn");
INSERT INTO developer (developer_id, developer_name) VALUES ("d250", "Dominique Grieshofer");
INSERT INTO developer (developer_id, developer_name) VALUES ("d251", "DotEmu");
INSERT INTO developer (developer_id, developer_name) VALUES ("d252", "DotEmu SAS.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d253", "Double Damage Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d254", "Double Fine Productions");
INSERT INTO developer (developer_id, developer_name) VALUES ("d255", "Double Helix Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d256", "DoubleBear Productions");
INSERT INTO developer (developer_id, developer_name) VALUES ("d257", "DoubleDutch Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d258", "Dovetail Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d259", "Dry Cactus");
INSERT INTO developer (developer_id, developer_name) VALUES ("d260", "Duck");
INSERT INTO developer (developer_id, developer_name) VALUES ("d261", "DyingCat");
INSERT INTO developer (developer_id, developer_name) VALUES ("d262", "Dylan Fitterer");
INSERT INTO developer (developer_id, developer_name) VALUES ("d263", "Dylan Hunt, 'Xblade'");
INSERT INTO developer (developer_id, developer_name) VALUES ("d264", "Dymchick1");
INSERT INTO developer (developer_id, developer_name) VALUES ("d265", "Dynamic Pixels");
INSERT INTO developer (developer_id, developer_name) VALUES ("d266", "EA - Maxis");
INSERT INTO developer (developer_id, developer_name) VALUES ("d267", "EA Black Box");
INSERT INTO developer (developer_id, developer_name) VALUES ("d268", "EA Los Angeles");
INSERT INTO developer (developer_id, developer_name) VALUES ("d269", "EA Redwood Shores");
INSERT INTO developer (developer_id, developer_name) VALUES ("d270", "EHTechnology");
INSERT INTO developer (developer_id, developer_name) VALUES ("d271", "EQ-Games , Pixel Dash Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d272", "EarthWork Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d273", "EasyGameStation");
INSERT INTO developer (developer_id, developer_name) VALUES ("d274", "EcoGames");
INSERT INTO developer (developer_id, developer_name) VALUES ("d275", "Edmund McMillen");
INSERT INTO developer (developer_id, developer_name) VALUES ("d276", "Edmund McMillen and Florian Himsl");
INSERT INTO developer (developer_id, developer_name) VALUES ("d277", "Eduard Mirica");
INSERT INTO developer (developer_id, developer_name) VALUES ("d278", "Eek! Games, LLC");
INSERT INTO developer (developer_id, developer_name) VALUES ("d279", "Efecto Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d280", "EfimovMax");
INSERT INTO developer (developer_id, developer_name) VALUES ("d281", "Eggcode");
INSERT INTO developer (developer_id, developer_name) VALUES ("d282", "Egidijus Bachur");
INSERT INTO developer (developer_id, developer_name) VALUES ("d283", "Egosoft");
INSERT INTO developer (developer_id, developer_name) VALUES ("d284", "Eidos Montreal");
INSERT INTO developer (developer_id, developer_name) VALUES ("d285", "Eidos-Montral");
INSERT INTO developer (developer_id, developer_name) VALUES ("d286", "Eko Software");
INSERT INTO developer (developer_id, developer_name) VALUES ("d287", "Elemental Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d288", "Eleon Game Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d289", "Elixir Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d290", "Elsa Hunt, 'FieryElsa'");
INSERT INTO developer (developer_id, developer_name) VALUES ("d291", "Endnight Games Ltd");
INSERT INTO developer (developer_id, developer_name) VALUES ("d292", "Ensemble Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d293", "Entrada Interactive LLC");
INSERT INTO developer (developer_id, developer_name) VALUES ("d294", "Epic Games, Inc.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d295", "Eric Hartman");
INSERT INTO developer (developer_id, developer_name) VALUES ("d296", "Eternity Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d297", "Ethrea Dreams");
INSERT INTO developer (developer_id, developer_name) VALUES ("d298", "Eugen Systems");
INSERT INTO developer (developer_id, developer_name) VALUES ("d299", "Evermore Game Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d300", "Evgeny Shcherbakov");
INSERT INTO developer (developer_id, developer_name) VALUES ("d301", "Evil Tortilla Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d302", "Expansive Worlds");
INSERT INTO developer (developer_id, developer_name) VALUES ("d303", "FELISTELLA Co., Ltd.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d304", "Fabio Ferrara");
INSERT INTO developer (developer_id, developer_name) VALUES ("d305", "Facepunch Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d306", "Failbetter Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d307", "Falcon Development");
INSERT INTO developer (developer_id, developer_name) VALUES ("d308", "Fancy Bytes, Reactor");
INSERT INTO developer (developer_id, developer_name) VALUES ("d309", "FantaBlade Network");
INSERT INTO developer (developer_id, developer_name) VALUES ("d310", "Fatbot Games, s. r. o.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d311", "Fatshark");
INSERT INTO developer (developer_id, developer_name) VALUES ("d312", "Felistella");
INSERT INTO developer (developer_id, developer_name) VALUES ("d313", "Fenix Fire Entertainment");
INSERT INTO developer (developer_id, developer_name) VALUES ("d314", "Feral Interactive (Linux)");
INSERT INTO developer (developer_id, developer_name) VALUES ("d315", "Feral Interactive (Mac)");
INSERT INTO developer (developer_id, developer_name) VALUES ("d316", "Feral Interactive (Mac/Linux)");
INSERT INTO developer (developer_id, developer_name) VALUES ("d317", "Fifth Dimension Company");
INSERT INTO developer (developer_id, developer_name) VALUES ("d318", "Firaxis Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d319", "Fire Hose Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d320", "FireFly Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d321", "Firehawk Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d322", "Fireproof Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d323", "Fishing Cactus");
INSERT INTO developer (developer_id, developer_name) VALUES ("d324", "Fixer Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d325", "Flamebait Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d326", "Flashback Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d327", "Florastamine");
INSERT INTO developer (developer_id, developer_name) VALUES ("d328", "Flump Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d329", "Flying Wild Hog");
INSERT INTO developer (developer_id, developer_name) VALUES ("d330", "Fool's Theory");
INSERT INTO developer (developer_id, developer_name) VALUES ("d331", "Forgotten Empires");
INSERT INTO developer (developer_id, developer_name) VALUES ("d332", "Forward Development, Ltd.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d333", "Four Winged Studio");
INSERT INTO developer (developer_id, developer_name) VALUES ("d334", "Free Lives");
INSERT INTO developer (developer_id, developer_name) VALUES ("d335", "Freebird Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d336", "Freehold Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d337", "Frictional Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d338", "Frisky Fatal Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d339", "Frogwares");
INSERT INTO developer (developer_id, developer_name) VALUES ("d340", "FromSoftware, Inc");
INSERT INTO developer (developer_id, developer_name) VALUES ("d341", "Frontier Developments");
INSERT INTO developer (developer_id, developer_name) VALUES ("d342", "Frozenbyte");
INSERT INTO developer (developer_id, developer_name) VALUES ("d343", "Funcom");
INSERT INTO developer (developer_id, developer_name) VALUES ("d344", "Fury Software");
INSERT INTO developer (developer_id, developer_name) VALUES ("d345", "GDNomad");
INSERT INTO developer (developer_id, developer_name) VALUES ("d346", "GSC Game World");
INSERT INTO developer (developer_id, developer_name) VALUES ("d347", "Gaddy Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d348", "Gaijin Entertainment");
INSERT INTO developer (developer_id, developer_name) VALUES ("d349", "Galactic Cafe");
INSERT INTO developer (developer_id, developer_name) VALUES ("d350", "Gambrinous");
INSERT INTO developer (developer_id, developer_name) VALUES ("d351", "Game Grumps");
INSERT INTO developer (developer_id, developer_name) VALUES ("d352", "Game in a Bottle");
INSERT INTO developer (developer_id, developer_name) VALUES ("d353", "Game-Labs");
INSERT INTO developer (developer_id, developer_name) VALUES ("d354", "GamersHype Productions");
INSERT INTO developer (developer_id, developer_name) VALUES ("d355", "Games Farm");
INSERT INTO developer (developer_id, developer_name) VALUES ("d356", "Gaming Minds Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d357", "Gamious");
INSERT INTO developer (developer_id, developer_name) VALUES ("d358", "Gas Powered Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d359", "Gaslamp Games, Inc.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d360", "Gearbox Software");
INSERT INTO developer (developer_id, developer_name) VALUES ("d361", "Gears for Breakfast");
INSERT INTO developer (developer_id, developer_name) VALUES ("d362", "GemaYue");
INSERT INTO developer (developer_id, developer_name) VALUES ("d363", "Ghost Town Games Ltd.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d364", "GhostShark");
INSERT INTO developer (developer_id, developer_name) VALUES ("d365", "Giant Army");
INSERT INTO developer (developer_id, developer_name) VALUES ("d366", "Giant Fox Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d367", "Giant Sparrow");
INSERT INTO developer (developer_id, developer_name) VALUES ("d368", "Giant Squid");
INSERT INTO developer (developer_id, developer_name) VALUES ("d369", "Giants Software");
INSERT INTO developer (developer_id, developer_name) VALUES ("d370", "Giulia Airoldi");
INSERT INTO developer (developer_id, developer_name) VALUES ("d371", "Goldhawk Interactive");
INSERT INTO developer (developer_id, developer_name) VALUES ("d372", "GolemLabs");
INSERT INTO developer (developer_id, developer_name) VALUES ("d373", "Gray Matter Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d374", "Greenheart Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d375", "Grey Alien Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d376", "Grimlore Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d377", "Gunfire Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d378", "HB Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d379", "HCP Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d380", "HFM Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d381", "HL-Galgame");
INSERT INTO developer (developer_id, developer_name) VALUES ("d382", "Haemimont Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d383", "Halfbrick Studios Pty Ltd");
INSERT INTO developer (developer_id, developer_name) VALUES ("d384", "Hardlight");
INSERT INTO developer (developer_id, developer_name) VALUES ("d385", "Harebrained Schemes");
INSERT INTO developer (developer_id, developer_name) VALUES ("d386", "Headcannon");
INSERT INTO developer (developer_id, developer_name) VALUES ("d387", "Heart Machine");
INSERT INTO developer (developer_id, developer_name) VALUES ("d388", "Hello Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d389", "Heluo Studio");
INSERT INTO developer (developer_id, developer_name) VALUES ("d390", "Hidden Path Entertainment");
INSERT INTO developer (developer_id, developer_name) VALUES ("d391", "High Voltage Software");
INSERT INTO developer (developer_id, developer_name) VALUES ("d392", "Hinterland Studio Inc.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d393", "Hollowings");
INSERT INTO developer (developer_id, developer_name) VALUES ("d394", "Hopoo Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d395", "Housemarque");
INSERT INTO developer (developer_id, developer_name) VALUES ("d396", "Hovgaard Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d397", "Humble Hearts LLC");
INSERT INTO developer (developer_id, developer_name) VALUES ("d398", "HuniePot");
INSERT INTO developer (developer_id, developer_name) VALUES ("d399", "Hunter Studio");
INSERT INTO developer (developer_id, developer_name) VALUES ("d400", "HypeTrain Digital");
INSERT INTO developer (developer_id, developer_name) VALUES ("d401", "I-Illusions");
INSERT INTO developer (developer_id, developer_name) VALUES ("d402", "I-deal Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d403", "IDEA FACTORY");
INSERT INTO developer (developer_id, developer_name) VALUES ("d404", "IDEA FACTORY Co., Ltd.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d405", "IMGN.PRO");
INSERT INTO developer (developer_id, developer_name) VALUES ("d406", "IPACS");
INSERT INTO developer (developer_id, developer_name) VALUES ("d407", "IR Studio");
INSERT INTO developer (developer_id, developer_name) VALUES ("d408", "IV Productions");
INSERT INTO developer (developer_id, developer_name) VALUES ("d409", "Idea Cabin");
INSERT INTO developer (developer_id, developer_name) VALUES ("d410", "Idea Factory");
INSERT INTO developer (developer_id, developer_name) VALUES ("d411", "Ilja Saburov");
INSERT INTO developer (developer_id, developer_name) VALUES ("d412", "IllFonic");
INSERT INTO developer (developer_id, developer_name) VALUES ("d413", "Illusion Softworks");
INSERT INTO developer (developer_id, developer_name) VALUES ("d414", "Illwinter Game Design");
INSERT INTO developer (developer_id, developer_name) VALUES ("d415", "Image & Form Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d416", "Imperium42 Game Studio");
INSERT INTO developer (developer_id, developer_name) VALUES ("d417", "Impressions Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d418", "Infinite Dreams");
INSERT INTO developer (developer_id, developer_name) VALUES ("d419", "Infinite Fall");
INSERT INTO developer (developer_id, developer_name) VALUES ("d420", "Infinity Ward");
INSERT INTO developer (developer_id, developer_name) VALUES ("d421", "Ink Stains Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d422", "Ino-Co Plus");
INSERT INTO developer (developer_id, developer_name) VALUES ("d423", "Instinct Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d424", "Interplay Inc.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d425", "Introversion Software");
INSERT INTO developer (developer_id, developer_name) VALUES ("d426", "Io-Interactive A/S");
INSERT INTO developer (developer_id, developer_name) VALUES ("d427", "Ion Storm");
INSERT INTO developer (developer_id, developer_name) VALUES ("d428", "Ionized Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d429", "Iron Galaxy");
INSERT INTO developer (developer_id, developer_name) VALUES ("d430", "Iron Lore Entertainment");
INSERT INTO developer (developer_id, developer_name) VALUES ("d431", "IronOak Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d432", "Ironclad Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d433", "Ironhide Game Studio");
INSERT INTO developer (developer_id, developer_name) VALUES ("d434", "Irrational Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d435", "JDRumble");
INSERT INTO developer (developer_id, developer_name) VALUES ("d436", "JIW-Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d437", "Jackbox Games, Inc.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d438", "Jan Zelen");
INSERT INTO developer (developer_id, developer_name) VALUES ("d439", "Jason Lovett");
INSERT INTO developer (developer_id, developer_name) VALUES ("d440", "Jaywalkers Interactive");
INSERT INTO developer (developer_id, developer_name) VALUES ("d441", "JetCat Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d442", "Jochen Terstiege");
INSERT INTO developer (developer_id, developer_name) VALUES ("d443", "Joey Drew Studios Inc.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d444", "John Wizard");
INSERT INTO developer (developer_id, developer_name) VALUES ("d445", "Joran Vergoessen");
INSERT INTO developer (developer_id, developer_name) VALUES ("d446", "Jundroo, LLC");
INSERT INTO developer (developer_id, developer_name) VALUES ("d447", "Just Add Water (Developments), Ltd.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d448", "Jutsu Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d449", "K Bros Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d450", "KADOKAWA");
INSERT INTO developer (developer_id, developer_name) VALUES ("d451", "KADOKAWA GAMES / GRASSHOPPER MANUFACTURE");
INSERT INTO developer (developer_id, developer_name) VALUES ("d452", "KAGAMI WORKs");
INSERT INTO developer (developer_id, developer_name) VALUES ("d453", "KAIKO");
INSERT INTO developer (developer_id, developer_name) VALUES ("d454", "KHB-Soft");
INSERT INTO developer (developer_id, developer_name) VALUES ("d455", "KOEI TECMO GAMES CO., LTD.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d456", "KT Racing");
INSERT INTO developer (developer_id, developer_name) VALUES ("d457", "Kaos Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d458", "Katauri Interactive");
INSERT INTO developer (developer_id, developer_name) VALUES ("d459", "Keen Software House");
INSERT INTO developer (developer_id, developer_name) VALUES ("d460", "KillHouse Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d461", "Killerfish Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d462", "Killmonday Games AB");
INSERT INTO developer (developer_id, developer_name) VALUES ("d463", "Kite Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d464", "Klei Entertainment");
INSERT INTO developer (developer_id, developer_name) VALUES ("d465", "Knuckle Cracker");
INSERT INTO developer (developer_id, developer_name) VALUES ("d466", "Konami Digital Entertainment");
INSERT INTO developer (developer_id, developer_name) VALUES ("d467", "Krzysztof Dycha");
INSERT INTO developer (developer_id, developer_name) VALUES ("d468", "Kunos Simulazioni");
INSERT INTO developer (developer_id, developer_name) VALUES ("d469", "Kverta");
INSERT INTO developer (developer_id, developer_name) VALUES ("d470", "LAN - GAMES EOOD");
INSERT INTO developer (developer_id, developer_name) VALUES ("d471", "LEVER Software");
INSERT INTO developer (developer_id, developer_name) VALUES ("d472", "LVGameDev LLC");
INSERT INTO developer (developer_id, developer_name) VALUES ("d473", "Lab Zero Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d474", "Landfall");
INSERT INTO developer (developer_id, developer_name) VALUES ("d475", "Landfall West");
INSERT INTO developer (developer_id, developer_name) VALUES ("d476", "Landon Podbielski");
INSERT INTO developer (developer_id, developer_name) VALUES ("d477", "Lantana Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d478", "Lapovich");
INSERT INTO developer (developer_id, developer_name) VALUES ("d479", "Larian Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d480", "Lars van Dorenvanck");
INSERT INTO developer (developer_id, developer_name) VALUES ("d481", "Lavaboots Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d482", "Lazy Bear Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d483", "League of Geeks");
INSERT INTO developer (developer_id, developer_name) VALUES ("d484", "Leo B");
INSERT INTO developer (developer_id, developer_name) VALUES ("d485", "Leonard Menchiari");
INSERT INTO developer (developer_id, developer_name) VALUES ("d486", "Licorice");
INSERT INTO developer (developer_id, developer_name) VALUES ("d487", "Lighthouse Games Studio");
INSERT INTO developer (developer_id, developer_name) VALUES ("d488", "Limbic Entertainment");
INSERT INTO developer (developer_id, developer_name) VALUES ("d489", "Lince Works");
INSERT INTO developer (developer_id, developer_name) VALUES ("d490", "Lino Slahuschek");
INSERT INTO developer (developer_id, developer_name) VALUES ("d491", "Lion Shield, LLC");
INSERT INTO developer (developer_id, developer_name) VALUES ("d492", "Lion game Lion");
INSERT INTO developer (developer_id, developer_name) VALUES ("d493", "Lionhead Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d494", "Little Cat Feet");
INSERT INTO developer (developer_id, developer_name) VALUES ("d495", "Little Green Men Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d496", "Little Stone Software");
INSERT INTO developer (developer_id, developer_name) VALUES ("d497", "Logic Artists");
INSERT INTO developer (developer_id, developer_name) VALUES ("d498", "Loiste Interactive");
INSERT INTO developer (developer_id, developer_name) VALUES ("d499", "LongYou Game Studio");
INSERT INTO developer (developer_id, developer_name) VALUES ("d500", "LuGus Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d501", "Lucas Dieguez");
INSERT INTO developer (developer_id, developer_name) VALUES ("d502", "Lucas Pope");
INSERT INTO developer (developer_id, developer_name) VALUES ("d503", "LucasArts");
INSERT INTO developer (developer_id, developer_name) VALUES ("d504", "Ludeon Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d505", "Lukas Rustemeyer");
INSERT INTO developer (developer_id, developer_name) VALUES ("d506", "M2H");
INSERT INTO developer (developer_id, developer_name) VALUES ("d507", "MAGES. Inc.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d508", "MR-Software GbR");
INSERT INTO developer (developer_id, developer_name) VALUES ("d509", "Machine Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d510", "Madgarden");
INSERT INTO developer (developer_id, developer_name) VALUES ("d511", "Madruga Works");
INSERT INTO developer (developer_id, developer_name) VALUES ("d512", "Magicbane");
INSERT INTO developer (developer_id, developer_name) VALUES ("d513", "Martin Ivanov");
INSERT INTO developer (developer_id, developer_name) VALUES ("d514", "Massive Entertainment");
INSERT INTO developer (developer_id, developer_name) VALUES ("d515", "Mastfire Studios Pty Ltd");
INSERT INTO developer (developer_id, developer_name) VALUES ("d516", "Matt Dabrowski");
INSERT INTO developer (developer_id, developer_name) VALUES ("d517", "Matt Roszak");
INSERT INTO developer (developer_id, developer_name) VALUES ("d518", "Matvey Sakharovskiy");
INSERT INTO developer (developer_id, developer_name) VALUES ("d519", "Maximus.ez");
INSERT INTO developer (developer_id, developer_name) VALUES ("d520", "Maxis");
INSERT INTO developer (developer_id, developer_name) VALUES ("d521", "Mega Crit Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d522", "MercurySteam");
INSERT INTO developer (developer_id, developer_name) VALUES ("d523", "MercurySteam - Climax Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d524", "MicroProse Software, Inc");
INSERT INTO developer (developer_id, developer_name) VALUES ("d525", "Microblast Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d526", "Microids");
INSERT INTO developer (developer_id, developer_name) VALUES ("d527", "Microsoft Game Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d528", "Milestone S.r.l.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d529", "Mimimi Productions");
INSERT INTO developer (developer_id, developer_name) VALUES ("d530", "MinMax Games Ltd.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d531", "Mindillusion");
INSERT INTO developer (developer_id, developer_name) VALUES ("d532", "Minskworks");
INSERT INTO developer (developer_id, developer_name) VALUES ("d533", "Mohawk Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d534", "Monochrome, Inc");
INSERT INTO developer (developer_id, developer_name) VALUES ("d535", "Monolith");
INSERT INTO developer (developer_id, developer_name) VALUES ("d536", "Monolith Productions");
INSERT INTO developer (developer_id, developer_name) VALUES ("d537", "Monolith Productions, Inc.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d538", "Monomi Park");
INSERT INTO developer (developer_id, developer_name) VALUES ("d539", "Moon Studios GmbH");
INSERT INTO developer (developer_id, developer_name) VALUES ("d540", "Moonlight Mouse");
INSERT INTO developer (developer_id, developer_name) VALUES ("d541", "Mothership Entertainment LLC");
INSERT INTO developer (developer_id, developer_name) VALUES ("d542", "Motion Twin");
INSERT INTO developer (developer_id, developer_name) VALUES ("d543", "Mouldy Toof Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d544", "MrCiastku");
INSERT INTO developer (developer_id, developer_name) VALUES ("d545", "MuHa Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d546", "N3V Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d547", "NEKO WORKs");
INSERT INTO developer (developer_id, developer_name) VALUES ("d548", "NEXT Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d549", "NEZOS GAMES");
INSERT INTO developer (developer_id, developer_name) VALUES ("d550", "NGD Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d551", "Nadeo");
INSERT INTO developer (developer_id, developer_name) VALUES ("d552", "Natsume Inc.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d553", "NedoStudio");
INSERT INTO developer (developer_id, developer_name) VALUES ("d554", "Neko Climax Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d555", "NeocoreGames");
INSERT INTO developer (developer_id, developer_name) VALUES ("d556", "Nerial");
INSERT INTO developer (developer_id, developer_name) VALUES ("d557", "Netcore Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d558", "NetherRealm Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d559", "New Reality Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d560", "New World Interactive");
INSERT INTO developer (developer_id, developer_name) VALUES ("d561", "Night School Studio");
INSERT INTO developer (developer_id, developer_name) VALUES ("d562", "Nihon Falcom");
INSERT INTO developer (developer_id, developer_name) VALUES ("d563", "Nikita Nefedov");
INSERT INTO developer (developer_id, developer_name) VALUES ("d564", "Nikolai Patrakov");
INSERT INTO developer (developer_id, developer_name) VALUES ("d565", "Ninja Kiwi");
INSERT INTO developer (developer_id, developer_name) VALUES ("d566", "Ninja Theory");
INSERT INTO developer (developer_id, developer_name) VALUES ("d567", "Nippon Ichi Software, Inc.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d568", "Nival");
INSERT INTO developer (developer_id, developer_name) VALUES ("d569", "No Brakes Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d570", "Noio");
INSERT INTO developer (developer_id, developer_name) VALUES ("d571", "Nomad Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d572", "Northway Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d573", "Nuke Nine");
INSERT INTO developer (developer_id, developer_name) VALUES ("d574", "Nuked Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d575", "Numantian Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d576", "Nuno Donato");
INSERT INTO developer (developer_id, developer_name) VALUES ("d577", "Nvizzio Creations");
INSERT INTO developer (developer_id, developer_name) VALUES ("d578", "ONEONE1");
INSERT INTO developer (developer_id, developer_name) VALUES ("d579", "OVERKILL - a Starbreeze Studio.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d580", "Obsidian Entertainment");
INSERT INTO developer (developer_id, developer_name) VALUES ("d581", "Oddworld Inhabitants");
INSERT INTO developer (developer_id, developer_name) VALUES ("d582", "Old B1ood");
INSERT INTO developer (developer_id, developer_name) VALUES ("d583", "Ole Lange");
INSERT INTO developer (developer_id, developer_name) VALUES ("d584", "Olli Harjola, Otto Hantula, Tom Jubert, Carlo Castellano");
INSERT INTO developer (developer_id, developer_name) VALUES ("d585", "Oovee Game Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d586", "Orange_Juice");
INSERT INTO developer (developer_id, developer_name) VALUES ("d587", "Orbcreation");
INSERT INTO developer (developer_id, developer_name) VALUES ("d588", "Origin8 Technologies Ltd.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d589", "Other Ocean Interactive");
INSERT INTO developer (developer_id, developer_name) VALUES ("d590", "Out of the Park Developments");
INSERT INTO developer (developer_id, developer_name) VALUES ("d591", "Outlands");
INSERT INTO developer (developer_id, developer_name) VALUES ("d592", "Overhype Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d593", "Owlchemy Labs");
INSERT INTO developer (developer_id, developer_name) VALUES ("d594", "Oxide Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d595", "PERFECT PARALLEL");
INSERT INTO developer (developer_id, developer_name) VALUES ("d596", "PUBG Corporation");
INSERT INTO developer (developer_id, developer_name) VALUES ("d597", "PagodaWest Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d598", "Paleno Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d599", "PanGuoJun");
INSERT INTO developer (developer_id, developer_name) VALUES ("d600", "Panda Indie Studio");
INSERT INTO developer (developer_id, developer_name) VALUES ("d601", "Pandemic Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d602", "Panoramik Inc");
INSERT INTO developer (developer_id, developer_name) VALUES ("d603", "Paradox Development Studio");
INSERT INTO developer (developer_id, developer_name) VALUES ("d604", "PatchNoteStudio");
INSERT INTO developer (developer_id, developer_name) VALUES ("d605", "Pathea Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d606", "Payload Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d607", "Perfuse Entertainment");
INSERT INTO developer (developer_id, developer_name) VALUES ("d608", "Permadeath");
INSERT INTO developer (developer_id, developer_name) VALUES ("d609", "Perun Creative");
INSERT INTO developer (developer_id, developer_name) VALUES ("d610", "Petrodiy-Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d611", "Petroglyph");
INSERT INTO developer (developer_id, developer_name) VALUES ("d612", "Phanom Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d613", "Phenomic");
INSERT INTO developer (developer_id, developer_name) VALUES ("d614", "Pieces Interactive");
INSERT INTO developer (developer_id, developer_name) VALUES ("d615", "Pinokl Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d616", "Pipliz");
INSERT INTO developer (developer_id, developer_name) VALUES ("d617", "Piranha Bytes");
INSERT INTO developer (developer_id, developer_name) VALUES ("d618", "Pixel Ferrets");
INSERT INTO developer (developer_id, developer_name) VALUES ("d619", "Pixel Gangsta Studio");
INSERT INTO developer (developer_id, developer_name) VALUES ("d620", "PixelTail Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d621", "Planetary Annihilation Inc");
INSERT INTO developer (developer_id, developer_name) VALUES ("d622", "PlatinumGames");
INSERT INTO developer (developer_id, developer_name) VALUES ("d623", "PlatinumGames Inc.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d624", "Playdead");
INSERT INTO developer (developer_id, developer_name) VALUES ("d625", "Playdek, Inc.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d626", "Playsport Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d627", "Playtonic Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d628", "Pocketwatch Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d629", "Polytron Corporation");
INSERT INTO developer (developer_id, developer_name) VALUES ("d630", "PopCap Games, Inc.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d631", "PopTop");
INSERT INTO developer (developer_id, developer_name) VALUES ("d632", "Positech Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d633", "Powerhoof");
INSERT INTO developer (developer_id, developer_name) VALUES ("d634", "Prideful Sloth");
INSERT INTO developer (developer_id, developer_name) VALUES ("d635", "ProGames Studio");
INSERT INTO developer (developer_id, developer_name) VALUES ("d636", "Project 'The Game'");
INSERT INTO developer (developer_id, developer_name) VALUES ("d637", "ProjectorGames");
INSERT INTO developer (developer_id, developer_name) VALUES ("d638", "Proteus Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d639", "Psyonix, Inc.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d640", "Pub Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d641", "Purple Lamp Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d642", "Pyro Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d643", "QLOC");
INSERT INTO developer (developer_id, developer_name) VALUES ("d644", "QuickSave");
INSERT INTO developer (developer_id, developer_name) VALUES ("d645", "REX PEX GAMES");
INSERT INTO developer (developer_id, developer_name) VALUES ("d646", "ROCKFISH Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d647", "RPG Video");
INSERT INTO developer (developer_id, developer_name) VALUES ("d648", "Raconteur Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d649", "Radiant Entertainment");
INSERT INTO developer (developer_id, developer_name) VALUES ("d650", "Radical Entertainment");
INSERT INTO developer (developer_id, developer_name) VALUES ("d651", "Radical Fish Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d652", "Rain Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d653", "Rainbow Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d654", "Rake in Grass");
INSERT INTO developer (developer_id, developer_name) VALUES ("d655", "Rasul Mono");
INSERT INTO developer (developer_id, developer_name) VALUES ("d656", "Raven Software");
INSERT INTO developer (developer_id, developer_name) VALUES ("d657", "Raymond Doerr");
INSERT INTO developer (developer_id, developer_name) VALUES ("d658", "Reality Pump");
INSERT INTO developer (developer_id, developer_name) VALUES ("d659", "Reality Pump Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d660", "Realmforge Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d661", "Rebellion");
INSERT INTO developer (developer_id, developer_name) VALUES ("d662", "Red Barrels");
INSERT INTO developer (developer_id, developer_name) VALUES ("d663", "Red Dot Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d664", "Red Hook Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d665", "Red Thread Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d666", "RedCandleGames");
INSERT INTO developer (developer_id, developer_name) VALUES ("d667", "RedLynx, in collaboration with  Ubisoft Shanghai, Ubisoft Kiev");
INSERT INTO developer (developer_id, developer_name) VALUES ("d668", "Reflections");
INSERT INTO developer (developer_id, developer_name) VALUES ("d669", "Reikon Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d670", "Reiza Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d671", "Related Designs");
INSERT INTO developer (developer_id, developer_name) VALUES ("d672", "Relic");
INSERT INTO developer (developer_id, developer_name) VALUES ("d673", "Relic Entertainment");
INSERT INTO developer (developer_id, developer_name) VALUES ("d674", "Remedy Entertainment");
INSERT INTO developer (developer_id, developer_name) VALUES ("d675", "Renamilanesi");
INSERT INTO developer (developer_id, developer_name) VALUES ("d676", "Renato Milanesi");
INSERT INTO developer (developer_id, developer_name) VALUES ("d677", "Retrific");
INSERT INTO developer (developer_id, developer_name) VALUES ("d678", "Revolution Software Ltd");
INSERT INTO developer (developer_id, developer_name) VALUES ("d679", "Riviysky");
INSERT INTO developer (developer_id, developer_name) VALUES ("d680", "Robert Alvarez");
INSERT INTO developer (developer_id, developer_name) VALUES ("d681", "Robot Entertainment");
INSERT INTO developer (developer_id, developer_name) VALUES ("d682", "Robot Gentleman");
INSERT INTO developer (developer_id, developer_name) VALUES ("d683", "Rocketcat Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d684", "Rockstar Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d685", "Rockstar Leeds");
INSERT INTO developer (developer_id, developer_name) VALUES ("d686", "Rockstar New England");
INSERT INTO developer (developer_id, developer_name) VALUES ("d687", "Rockstar North");
INSERT INTO developer (developer_id, developer_name) VALUES ("d688", "Rockstar North / Toronto");
INSERT INTO developer (developer_id, developer_name) VALUES ("d689", "Rockstar Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d690", "Rockstar Toronto");
INSERT INTO developer (developer_id, developer_name) VALUES ("d691", "Rocksteady Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d692", "Rogue Factor");
INSERT INTO developer (developer_id, developer_name) VALUES ("d693", "Rooster Teeth Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d694", "Rotatipyra");
INSERT INTO developer (developer_id, developer_name) VALUES ("d695", "Rune Forge");
INSERT INTO developer (developer_id, developer_name) VALUES ("d696", "RuneStorm");
INSERT INTO developer (developer_id, developer_name) VALUES ("d697", "Runic Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d698", "Runner Duck");
INSERT INTO developer (developer_id, developer_name) VALUES ("d699", "Running With Scissors");
INSERT INTO developer (developer_id, developer_name) VALUES ("d700", "SANDLOT");
INSERT INTO developer (developer_id, developer_name) VALUES ("d701", "SCS Software");
INSERT INTO developer (developer_id, developer_name) VALUES ("d702", "SEGA");
INSERT INTO developer (developer_id, developer_name) VALUES ("d703", "SGTTB_Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d704", "SHIFT");
INSERT INTO developer (developer_id, developer_name) VALUES ("d705", "SNK CORPORATION");
INSERT INTO developer (developer_id, developer_name) VALUES ("d706", "SNK Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d707", "SOFF Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d708", "SUPERHOT Team");
INSERT INTO developer (developer_id, developer_name) VALUES ("d709", "Saber Interactive");
INSERT INTO developer (developer_id, developer_name) VALUES ("d710", "Sachonski");
INSERT INTO developer (developer_id, developer_name) VALUES ("d711", "Sarah Northway");
INSERT INTO developer (developer_id, developer_name) VALUES ("d712", "Sauropod Studio");
INSERT INTO developer (developer_id, developer_name) VALUES ("d713", "Schine, GmbH");
INSERT INTO developer (developer_id, developer_name) VALUES ("d714", "Scott Cawthon");
INSERT INTO developer (developer_id, developer_name) VALUES ("d715", "Screaming Bee");
INSERT INTO developer (developer_id, developer_name) VALUES ("d716", "Screeps");
INSERT INTO developer (developer_id, developer_name) VALUES ("d717", "Second Reality");
INSERT INTO developer (developer_id, developer_name) VALUES ("d718", "Secret Exit Ltd.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d719", "Secret Society Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d720", "Sekerin Productions");
INSERT INTO developer (developer_id, developer_name) VALUES ("d721", "Sergey Dvoynikov");
INSERT INTO developer (developer_id, developer_name) VALUES ("d722", "Shanghai huan zhen Info Tech Ltd");
INSERT INTO developer (developer_id, developer_name) VALUES ("d723", "SharF Co.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d724", "Shining Pixel Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d725", "Shining Rock Software LLC");
INSERT INTO developer (developer_id, developer_name) VALUES ("d726", "Shiro Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d727", "Shiver Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d728", "Silver Dollar Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d729", "SimTex");
INSERT INTO developer (developer_id, developer_name) VALUES ("d730", "Sith");
INSERT INTO developer (developer_id, developer_name) VALUES ("d731", "Sixteen Tons Entertainment");
INSERT INTO developer (developer_id, developer_name) VALUES ("d732", "Ska Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d733", "SkyBox Labs");
INSERT INTO developer (developer_id, developer_name) VALUES ("d734", "Skybox Labs");
INSERT INTO developer (developer_id, developer_name) VALUES ("d735", "Sledgehammer Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d736", "Slightly Mad Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d737", "Slikey Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d738", "Sloclap");
INSERT INTO developer (developer_id, developer_name) VALUES ("d739", "Slug Disco Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d740", "SmashGames");
INSERT INTO developer (developer_id, developer_name) VALUES ("d741", "SmiteWorks USA, LLC");
INSERT INTO developer (developer_id, developer_name) VALUES ("d742", "Snail Games USA");
INSERT INTO developer (developer_id, developer_name) VALUES ("d743", "SnowFlame");
INSERT INTO developer (developer_id, developer_name) VALUES ("d744", "Snowbird Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d745", "SoftWarWare");
INSERT INTO developer (developer_id, developer_name) VALUES ("d746", "Solecismic Software");
INSERT INTO developer (developer_id, developer_name) VALUES ("d747", "SomaSim");
INSERT INTO developer (developer_id, developer_name) VALUES ("d748", "Sometimes You");
INSERT INTO developer (developer_id, developer_name) VALUES ("d749", "Sonic Team");
INSERT INTO developer (developer_id, developer_name) VALUES ("d750", "South East Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d751", "Space Boat Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d752", "Space Cat Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d753", "Sparpweed");
INSERT INTO developer (developer_id, developer_name) VALUES ("d754", "Spiderling Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d755", "Spike Chunsoft Co., Ltd.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d756", "Spiral Game Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d757", "Splash Damage");
INSERT INTO developer (developer_id, developer_name) VALUES ("d758", "Split Polygon");
INSERT INTO developer (developer_id, developer_name) VALUES ("d759", "Sports Interactive");
INSERT INTO developer (developer_id, developer_name) VALUES ("d760", "Square Enix");
INSERT INTO developer (developer_id, developer_name) VALUES ("d761", "Stainless Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d762", "StalkerAlex");
INSERT INTO developer (developer_id, developer_name) VALUES ("d763", "Star Drifters");
INSERT INTO developer (developer_id, developer_name) VALUES ("d764", "StarSystemStudios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d765", "Starbreeze Studios AB");
INSERT INTO developer (developer_id, developer_name) VALUES ("d766", "Stardock Entertainment");
INSERT INTO developer (developer_id, developer_name) VALUES ("d767", "Stegersaurus Software Inc.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d768", "Stoic");
INSERT INTO developer (developer_id, developer_name) VALUES ("d769", "Stray Fawn Studio");
INSERT INTO developer (developer_id, developer_name) VALUES ("d770", "Studio 397");
INSERT INTO developer (developer_id, developer_name) VALUES ("d771", "Studio Wildcard");
INSERT INTO developer (developer_id, developer_name) VALUES ("d772", "Stygian Software");
INSERT INTO developer (developer_id, developer_name) VALUES ("d773", "Subset Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d774", "Sukeban Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d775", "Supergiant Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d776", "Survios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d777", "Suspicious Developments");
INSERT INTO developer (developer_id, developer_name) VALUES ("d778", "Sylvain Tegroeg");
INSERT INTO developer (developer_id, developer_name) VALUES ("d779", "Synaptic Insight Technology Systems");
INSERT INTO developer (developer_id, developer_name) VALUES ("d780", "Synnergy Circle Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d781", "System Era Softworks");
INSERT INTO developer (developer_id, developer_name) VALUES ("d782", "TABOT, inc.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d783", "THQ Nordic");
INSERT INTO developer (developer_id, developer_name) VALUES ("d784", "TML-Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d785", "TPP Studio");
INSERT INTO developer (developer_id, developer_name) VALUES ("d786", "TT Fusion");
INSERT INTO developer (developer_id, developer_name) VALUES ("d787", "TT Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d788", "TT Games Ltd");
INSERT INTO developer (developer_id, developer_name) VALUES ("d789", "TaleWorlds Entertainment");
INSERT INTO developer (developer_id, developer_name) VALUES ("d790", "Talentplace");
INSERT INTO developer (developer_id, developer_name) VALUES ("d791", "Tamsoft");
INSERT INTO developer (developer_id, developer_name) VALUES ("d792", "Tango Gameworks");
INSERT INTO developer (developer_id, developer_name) VALUES ("d793", "Targem Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d794", "Tarsier Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d795", "Tasharen Entertainment Inc.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d796", "Team 17 Digital Ltd");
INSERT INTO developer (developer_id, developer_name) VALUES ("d797", "Team Bondi");
INSERT INTO developer (developer_id, developer_name) VALUES ("d798", "Team Cherry");
INSERT INTO developer (developer_id, developer_name) VALUES ("d799", "Team Fractal Alligator");
INSERT INTO developer (developer_id, developer_name) VALUES ("d800", "Team Reptile");
INSERT INTO developer (developer_id, developer_name) VALUES ("d801", "Team17 Digital Ltd");
INSERT INTO developer (developer_id, developer_name) VALUES ("d802", "Techland");
INSERT INTO developer (developer_id, developer_name) VALUES ("d803", "Telltale Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d804", "Tero Lunkka");
INSERT INTO developer (developer_id, developer_name) VALUES ("d805", "Terrible Toybox");
INSERT INTO developer (developer_id, developer_name) VALUES ("d806", "Texel Raptor");
INSERT INTO developer (developer_id, developer_name) VALUES ("d807", "The Behemoth");
INSERT INTO developer (developer_id, developer_name) VALUES ("d808", "The Game Bakers");
INSERT INTO developer (developer_id, developer_name) VALUES ("d809", "The Gentlebros");
INSERT INTO developer (developer_id, developer_name) VALUES ("d810", "The Indie Stone");
INSERT INTO developer (developer_id, developer_name) VALUES ("d811", "The Light Sword Team");
INSERT INTO developer (developer_id, developer_name) VALUES ("d812", "The Lordz Games Studio");
INSERT INTO developer (developer_id, developer_name) VALUES ("d813", "The Sims Studio");
INSERT INTO developer (developer_id, developer_name) VALUES ("d814", "Thekla, Inc.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d815", "Thomas Biskup");
INSERT INTO developer (developer_id, developer_name) VALUES ("d816", "Thorngames");
INSERT INTO developer (developer_id, developer_name) VALUES ("d817", "Those Awesome Guys");
INSERT INTO developer (developer_id, developer_name) VALUES ("d818", "Thunder Lotus Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d819", "Timegate");
INSERT INTO developer (developer_id, developer_name) VALUES ("d820", "Timofey Shargorodskiy");
INSERT INTO developer (developer_id, developer_name) VALUES ("d821", "Tindalos Interactive");
INSERT INTO developer (developer_id, developer_name) VALUES ("d822", "Toast");
INSERT INTO developer (developer_id, developer_name) VALUES ("d823", "Tomorrow Corporation");
INSERT INTO developer (developer_id, developer_name) VALUES ("d824", "ToonTRAXX Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d825", "Topware Interactive");
INSERT INTO developer (developer_id, developer_name) VALUES ("d826", "Transhuman Design");
INSERT INTO developer (developer_id, developer_name) VALUES ("d827", "Trauma");
INSERT INTO developer (developer_id, developer_name) VALUES ("d828", "Traveller's Tales");
INSERT INTO developer (developer_id, developer_name) VALUES ("d829", "Trese Brothers");
INSERT INTO developer (developer_id, developer_name) VALUES ("d830", "Treyarch");
INSERT INTO developer (developer_id, developer_name) VALUES ("d831", "Trinket Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d832", "Triple.B.Titles");
INSERT INTO developer (developer_id, developer_name) VALUES ("d833", "Tripwire Interactive");
INSERT INTO developer (developer_id, developer_name) VALUES ("d834", "TrisPix Studio");
INSERT INTO developer (developer_id, developer_name) VALUES ("d835", "Triumph Studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d836", "Troika Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d837", "Tyler Glaiel");
INSERT INTO developer (developer_id, developer_name) VALUES ("d838", "U-Play Online");
INSERT INTO developer (developer_id, developer_name) VALUES ("d839", "Ubisoft");
INSERT INTO developer (developer_id, developer_name) VALUES ("d840", "Ubisoft - San Francisco");
INSERT INTO developer (developer_id, developer_name) VALUES ("d841", "Ubisoft Annecy");
INSERT INTO developer (developer_id, developer_name) VALUES ("d842", "Ubisoft Belgrade");
INSERT INTO developer (developer_id, developer_name) VALUES ("d843", "Ubisoft Bucharest");
INSERT INTO developer (developer_id, developer_name) VALUES ("d844", "Ubisoft Entertainment");
INSERT INTO developer (developer_id, developer_name) VALUES ("d845", "Ubisoft Kiev");
INSERT INTO developer (developer_id, developer_name) VALUES ("d846", "Ubisoft Milan");
INSERT INTO developer (developer_id, developer_name) VALUES ("d847", "Ubisoft Montpellier");
INSERT INTO developer (developer_id, developer_name) VALUES ("d848", "Ubisoft Montral");
INSERT INTO developer (developer_id, developer_name) VALUES ("d849", "Ubisoft Montreal");
INSERT INTO developer (developer_id, developer_name) VALUES ("d850", "Ubisoft Montreal, Massive Entertainment, and Ubisoft Shanghai");
INSERT INTO developer (developer_id, developer_name) VALUES ("d851", "Ubisoft Montreal, Red Storm, Shanghai, Toronto, Kiev");
INSERT INTO developer (developer_id, developer_name) VALUES ("d852", "Ubisoft Paris");
INSERT INTO developer (developer_id, developer_name) VALUES ("d853", "Ubisoft Pune");
INSERT INTO developer (developer_id, developer_name) VALUES ("d854", "Ubisoft Quebec");
INSERT INTO developer (developer_id, developer_name) VALUES ("d855", "Ubisoft Quebec, in collaboration with Ubisoft Annecy, Bucharest, Kiev, Montreal, Montpellier, Shanghai, Singapore, Sofia, Toronto studios");
INSERT INTO developer (developer_id, developer_name) VALUES ("d856", "Ubisoft San Francisco");
INSERT INTO developer (developer_id, developer_name) VALUES ("d857", "Ubisoft Sofia");
INSERT INTO developer (developer_id, developer_name) VALUES ("d858", "Ubisoft Toronto");
INSERT INTO developer (developer_id, developer_name) VALUES ("d859", "Ultra Runaway Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d860", "Uncle Frost Team");
INSERT INTO developer (developer_id, developer_name) VALUES ("d861", "Undead Labs");
INSERT INTO developer (developer_id, developer_name) VALUES ("d862", "Unicube");
INSERT INTO developer (developer_id, developer_name) VALUES ("d863", "United Front Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d864", "Unknown Worlds Entertainment");
INSERT INTO developer (developer_id, developer_name) VALUES ("d865", "Urban Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d866", "Ursa Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d867", "Valve");
INSERT INTO developer (developer_id, developer_name) VALUES ("d868", "VaragtP");
INSERT INTO developer (developer_id, developer_name) VALUES ("d869", "Vertigo Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d870", "Vertigo Gaming Inc.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d871", "Videocult");
INSERT INTO developer (developer_id, developer_name) VALUES ("d872", "Vigil Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d873", "Virtual Basement LLC");
INSERT INTO developer (developer_id, developer_name) VALUES ("d874", "Virtual Programming");
INSERT INTO developer (developer_id, developer_name) VALUES ("d875", "Virtual Programming (Linux)");
INSERT INTO developer (developer_id, developer_name) VALUES ("d876", "Visceral Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d877", "Visual Concepts");
INSERT INTO developer (developer_id, developer_name) VALUES ("d878", "VladCastillo");
INSERT INTO developer (developer_id, developer_name) VALUES ("d879", "Vladimir Shlapak");
INSERT INTO developer (developer_id, developer_name) VALUES ("d880", "Vlambeer");
INSERT INTO developer (developer_id, developer_name) VALUES ("d881", "Void games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d882", "Volition");
INSERT INTO developer (developer_id, developer_name) VALUES ("d883", "Vyacheslav Shilikhin");
INSERT INTO developer (developer_id, developer_name) VALUES ("d884", "WB Games Montreal");
INSERT INTO developer (developer_id, developer_name) VALUES ("d885", "WOLCEN Studio");
INSERT INTO developer (developer_id, developer_name) VALUES ("d886", "WarfareSims");
INSERT INTO developer (developer_id, developer_name) VALUES ("d887", "Warm Lamp Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d888", "Weappy Studio");
INSERT INTO developer (developer_id, developer_name) VALUES ("d889", "WeirdBeard");
INSERT INTO developer (developer_id, developer_name) VALUES ("d890", "Wenkly Studio Sp. z o.o.");
INSERT INTO developer (developer_id, developer_name) VALUES ("d891", "White Dog");
INSERT INTO developer (developer_id, developer_name) VALUES ("d892", "White Rabbit Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d893", "Winged Cloud");
INSERT INTO developer (developer_id, developer_name) VALUES ("d894", "Wojciech Krupinski");
INSERT INTO developer (developer_id, developer_name) VALUES ("d895", "Wonderstruck");
INSERT INTO developer (developer_id, developer_name) VALUES ("d896", "WrathSchneider");
INSERT INTO developer (developer_id, developer_name) VALUES ("d897", "Wulo Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d898", "YAGER");
INSERT INTO developer (developer_id, developer_name) VALUES ("d899", "Yacht Club Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d900", "YarGri");
INSERT INTO developer (developer_id, developer_name) VALUES ("d901", "Young Horses");
INSERT INTO developer (developer_id, developer_name) VALUES ("d902", "Yuke's Co., LTD");
INSERT INTO developer (developer_id, developer_name) VALUES ("d903", "Z-Software");
INSERT INTO developer (developer_id, developer_name) VALUES ("d904", "Zachtronics");
INSERT INTO developer (developer_id, developer_name) VALUES ("d905", "Zeno Rogue");
INSERT INTO developer (developer_id, developer_name) VALUES ("d906", "Zenz VR");
INSERT INTO developer (developer_id, developer_name) VALUES ("d907", "Zero Gravity");
INSERT INTO developer (developer_id, developer_name) VALUES ("d908", "Zillion Whales");
INSERT INTO developer (developer_id, developer_name) VALUES ("d909", "azimut team");
INSERT INTO developer (developer_id, developer_name) VALUES ("d910", "encurio");
INSERT INTO developer (developer_id, developer_name) VALUES ("d911", "exagongames");
INSERT INTO developer (developer_id, developer_name) VALUES ("d912", "iRacing");
INSERT INTO developer (developer_id, developer_name) VALUES ("d913", "iRacing.com Motorsport Simulations");
INSERT INTO developer (developer_id, developer_name) VALUES ("d914", "id Software");
INSERT INTO developer (developer_id, developer_name) VALUES ("d915", "inXile Entertainment");
INSERT INTO developer (developer_id, developer_name) VALUES ("d916", "kChamp Games");
INSERT INTO developer (developer_id, developer_name) VALUES ("d917", "oddonegames");
INSERT INTO developer (developer_id, developer_name) VALUES ("d918", "raptor lab");
INSERT INTO developer (developer_id, developer_name) VALUES ("d919", "tri-Ace");
INSERT INTO developer (developer_id, developer_name) VALUES ("d920", "weltenbauer. Software Entwicklung GmbH");

-- End of populate_developer_table.sql